application: interactiveinvoice
version: 1
runtime: python
api_version: 1

handlers:
- url: /invoice
  script: main.py

- url: /js
  static_dir: files/js

- url: /css/
  static_dir: css/

- url: /images
  static_dir: images/

- url: /*
  script: main.py