application: interactiveinvoice
version: 1
runtime: python
api_version: 1

handlers:
- url: /js
  static_dir: js/

- url: /css/
  static_dir: css/

- url: /images
  static_dir: images/

- url: /new
  script: main.py
  
- url: /invoice
  script: main.py  
  
- url: /
  script: main.py